#!/bin/bash

# Pulls languages from Transifex and creates .mo files
# Usage: dvk-build languages
languages()
{
	if [[ -e ".tx/config" ]]; then
		tx pull
	fi

	if [[ -d "languages" ]]; then
		for file in `find languages/. -name "*.po"` ; do msgfmt -o ${file/.po/.mo} $file; done

      if [[ -e ".git" ]]; then
         git add languages/.
         git commit -m "updated languages"
      fi;
	fi;


}

# Builds assets using Gulp or Grunt
# Usage: dvk-build assets
assets()
{
	# Install NPM deps
	if [ -e package.json ] && [ ! -d node_modules ]; then
		sudo npm install
	fi

	# Run Gulp
	if [ -e gulpfile.js ]; then
		gulp
	fi

	# Run Grunt
	if [ -e Gruntfile.js ];	then
		grunt
	fi

   if [[ -e ".git" ]]; then
   	git add assets/.
   	git commit -m "updated assets"]
   fi;
}

# Creates the Composer autoloader
# Usage: dvk-build autoloader
autoloader()
{
	# Run Composer
	if [ -e composer.json ]; then
			# Make sure dev-dependencies are not installed
			composer update --no-dev --prefer-dist --optimize-autoloader

			git add vendor/.
			git commit -m "updated autoloader"
	fi
}

$1