#!/bin/bash

# Bumps a version number
# Usage: wp-bump-version 3.0.0

# Require at least 1 parameter: Version
if [ "$#" -lt 1 ]; then
    echo "At least 1 parameter expected, $# found"
    exit 1;
fi

VERSION=$1

# Bump version in readme.txt, *.json en ./*.php files
sed -i.bak "s/Stable tag: .*/Stable tag: $VERSION/g" readme.txt
sed -i.bak "s/define( '\(.*\)_VERSION', .*/define( '\1_VERSION', '$VERSION' );/g; s/Version: .*/Version: $VERSION/g" *.php
sed -i.bak "s/\"version\": .*/\"version\": \"$VERSION\",/g" *.json

# Remove backup files
rm *.bak

# Add change to Git
git add readme.txt *.php *.json
git commit -m "Version bump to v$VERSION"
