#!/bin/bash

#########################################
# Prepares a plugin package for release #
#########################################

# Usage: wp-plugin-package $DIR $VERSION $DESTINATION
# Example: wp-plugin-package . 1.0 ~/releases

PLUGIN_DIRECTORY=$1
VERSION=$2

# Require at least 2 parameters: DIR and VERSION
if [ "$#" -lt 2 ]; then
    echo "At least 2 parameters expected, $# found"
    exit 1;
fi

if [[ ! -d "$PLUGIN_DIRECTORY"  ]]; then
	echo -e "Plugin directory does not exist"
	exit 1;
fi;

# Traverse into plugin directory
cd $PLUGIN_DIRECTORY
PLUGIN_NAME=${PWD##*/}
DEST=${3:-".."}
DEST="$DEST/$PLUGIN_NAME-$VERSION.zip"

# Build all the things, then bump version
if [[ -e "readme.txt" ]]; then
	wp-update-changelog
fi;

dvk-build languages
dvk-build assets
dvk-build autoloader
wp-bump-version $VERSION

# Add untracked changes
git add . -A
git commit -m "[Pre-Release] v$VERSION"

# Create zip file (excludes files from .gitattributes)
echo "Creating release package"
git archive master --format=zip --prefix="$PLUGIN_NAME/" --output="/tmp/$PLUGIN_NAME.zip"
mv "/tmp/$PLUGIN_NAME.zip" "$DEST"

echo "$DEST"