#!/bin/bash
PACKAGE=$1
SVN_DIR=${SVN_DIR:-"/tmp/svn"}
printf "\n";

# Find package
if [ ! -e $PACKAGE ]; then
	printf "Package $PACKAGE does not exist. \n\nRun wp-plugin-package on the Git folder to create it.\n";
	exit 1;
fi;

# Unzip to tmp location
echo "Unzipping package."
rm -rf /tmp/plugin-package/*
unzip -o $PACKAGE -d /tmp/plugin-package >/dev/null
cd /tmp/plugin-package/*

# find name & version number
NAME=${PWD##*/}
VERSION=$(cat *.php | grep "^Version: \(.*\)" | tr ' ' '\n' | tail -1)

if [ -z $VERSION ]; then
	echo "Unable to find version number - is the package corrupt?"
	exit 1;
fi;

# Print some info
echo "Plugin: $NAME";
echo "Version: $VERSION";
printf "\nProceed? (y): "
read CONFIRM
if [ "$CONFIRM" != "y" ]; then
	exit 1;
fi;

# Checkout SVN repo to some location
if [ ! -d "$SVN_DIR/$NAME" ]; then
	SVN_REPO="http://plugins.svn.wordpress.org/$NAME";
	svn checkout $SVN_REPO -N "/tmp/svn/$NAME" >/dev/null
fi;

cd "$SVN_DIR/$NAME";

svn update trunk >/dev/null

# Add our changes to ./trunk
rm -r trunk
cp -r "/tmp/plugin-package/$NAME/." trunk
svn add . --force --auto-props --parents --depth infinity -q

# Remove locally deleted files
svn st | grep ^! | awk '{print " --force "$2}' | xargs svn rm

# Copy trunk to ./tags/VERSION
# TODO

# Show status & ask for confirmation
svn status

printf "\nPush $NAME v$VERSION to WordPress.org? (y)"
read CONFIRM
if [ "$CONFIRM" != "y" ]; then
	exit 1;
fi;

# Push to .org
svn commit -m "v$VERSION";
