#!/bin/bash

# Vars
PACKAGE=$1
LOCATION=$2
API_URL=$3
API_DOWNLOAD_ID=$4

# Find package
if [ ! -e $PACKAGE ]; then
	printf "Package $PACKAGE does not exist. \n\nRun wp-plugin-package on the Git folder to create it.\n";
	exit 1;
fi;

# Unzip to tmp location & traverse into plugin dir
echo "Unzipping package."
rm -rf /tmp/plugin-package/*
unzip -o $PACKAGE -d /tmp/plugin-package >/dev/null
cd /tmp/plugin-package/*

# find name & version number
NAME=${PWD##*/}
VERSION=$(cat *.php | grep "^Version: \(.*\)" | tr ' ' '\n' | tail -1)

# Find changelog
# TODO
# grep "^== $VERSION (at least 1 newline, anything until next ^==)
CHANGELOG=$(cat CHANGELOG.md)
echo $CHANGELOG
exit 1;

if [ -z $VERSION ]; then
	echo "Unable to find version number - is the package corrupt?"
	exit 1;
fi;

# Print some info
echo "Plugin: $NAME";
echo "Version: $VERSION";
printf "\nProceed? (y): "
read CONFIRM
if [ "$CONFIRM" != "y" ]; then
	exit 1;
fi;

# Copy package to server
echo "Copying package to $LOCATION"
scp $PACKAGE $LOCATION

# Bump version via custom EDD API
echo "Bumping version to v$VERSION on $API_URL"
curl \
	--data-urlencode "api_key=$EDD_API_KEY" \
	--data "edd-api-action=bump-download-version&download_id=$API_DOWNLOAD_ID&new_version=$VERSION" \
	--data-urlencode "changelog=$CHANGELOG" $API_URL